/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.FinanceManager;

/**
 *
 * @author Dev
 */
public class SupplierPaymentFM extends javax.swing.JFrame {

    /**
     * Creates new form SupplierPaymentFM
     */
    public SupplierPaymentFM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SupplierPaymentFM_ttl = new javax.swing.JLabel();
        SupplierPaymentFM_searchttl = new javax.swing.JLabel();
        SupplierPaymentFM_searchfld = new javax.swing.JTextField();
        SupplierPaymentFM_searchbtn = new javax.swing.JButton();
        SupplierPaymentFM_filterttl = new javax.swing.JLabel();
        SupplierPaymentFM_filtercbx = new javax.swing.JComboBox<>();
        SupplierPaymentFM_posp = new javax.swing.JScrollPane();
        SupplierPaymentFM_potb = new javax.swing.JTable();
        SupplierPaymentFM_refreshbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(173, 203, 204));

        SupplierPaymentFM_ttl.setFont(new java.awt.Font("Arial Black", 2, 24)); // NOI18N
        SupplierPaymentFM_ttl.setForeground(new java.awt.Color(65, 76, 65));
        SupplierPaymentFM_ttl.setText("Supplier Payment Status");
        SupplierPaymentFM_ttl.setToolTipText("");

        SupplierPaymentFM_searchttl.setBackground(new java.awt.Color(65, 76, 65));
        SupplierPaymentFM_searchttl.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        SupplierPaymentFM_searchttl.setForeground(new java.awt.Color(65, 76, 65));
        SupplierPaymentFM_searchttl.setText("Enter your PO ID / Supplier Name / Item Code here");

        SupplierPaymentFM_searchfld.setBackground(new java.awt.Color(161, 205, 168));
        SupplierPaymentFM_searchfld.setForeground(new java.awt.Color(28, 35, 33));
        SupplierPaymentFM_searchfld.setToolTipText("");
        SupplierPaymentFM_searchfld.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SupplierPaymentFM_searchfld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierPaymentFM_searchfldActionPerformed(evt);
            }
        });

        SupplierPaymentFM_searchbtn.setBackground(new java.awt.Color(94, 101, 114));
        SupplierPaymentFM_searchbtn.setForeground(new java.awt.Color(238, 241, 239));
        SupplierPaymentFM_searchbtn.setText("Search");
        SupplierPaymentFM_searchbtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        SupplierPaymentFM_searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierPaymentFM_searchbtnActionPerformed(evt);
            }
        });

        SupplierPaymentFM_filterttl.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        SupplierPaymentFM_filterttl.setForeground(new java.awt.Color(55, 63, 81));
        SupplierPaymentFM_filterttl.setText("Filter by Payment Status");

        SupplierPaymentFM_filtercbx.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        SupplierPaymentFM_filtercbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Pending", "Paid", "Overdue" }));
        SupplierPaymentFM_filtercbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierPaymentFM_filtercbxActionPerformed(evt);
            }
        });

        SupplierPaymentFM_potb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "PO ID", "Supplier Name", "Item Code", "Quantity", "Order Date", "Approval Status"
            }
        ));
        SupplierPaymentFM_posp.setViewportView(SupplierPaymentFM_potb);

        SupplierPaymentFM_refreshbtn.setBackground(new java.awt.Color(94, 101, 114));
        SupplierPaymentFM_refreshbtn.setForeground(new java.awt.Color(238, 241, 239));
        SupplierPaymentFM_refreshbtn.setText("Refresh List");
        SupplierPaymentFM_refreshbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SupplierPaymentFM_refreshbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierPaymentFM_refreshbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SupplierPaymentFM_ttl, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(SupplierPaymentFM_searchttl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SupplierPaymentFM_searchfld, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(SupplierPaymentFM_searchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SupplierPaymentFM_posp, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SupplierPaymentFM_filterttl)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SupplierPaymentFM_filtercbx, 0, 100, Short.MAX_VALUE)
                                    .addComponent(SupplierPaymentFM_refreshbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SupplierPaymentFM_ttl)
                .addGap(18, 18, 18)
                .addComponent(SupplierPaymentFM_searchttl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SupplierPaymentFM_searchfld, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SupplierPaymentFM_searchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SupplierPaymentFM_posp, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(SupplierPaymentFM_filterttl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SupplierPaymentFM_filtercbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SupplierPaymentFM_refreshbtn)))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SupplierPaymentFM_searchfldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplierPaymentFM_searchfldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SupplierPaymentFM_searchfldActionPerformed

    private void SupplierPaymentFM_searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplierPaymentFM_searchbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SupplierPaymentFM_searchbtnActionPerformed

    private void SupplierPaymentFM_filtercbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplierPaymentFM_filtercbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SupplierPaymentFM_filtercbxActionPerformed

    private void SupplierPaymentFM_refreshbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplierPaymentFM_refreshbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SupplierPaymentFM_refreshbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupplierPaymentFM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupplierPaymentFM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupplierPaymentFM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupplierPaymentFM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupplierPaymentFM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> SupplierPaymentFM_filtercbx;
    private javax.swing.JLabel SupplierPaymentFM_filterttl;
    private javax.swing.JScrollPane SupplierPaymentFM_posp;
    private javax.swing.JTable SupplierPaymentFM_potb;
    private javax.swing.JButton SupplierPaymentFM_refreshbtn;
    private javax.swing.JButton SupplierPaymentFM_searchbtn;
    private javax.swing.JTextField SupplierPaymentFM_searchfld;
    private javax.swing.JLabel SupplierPaymentFM_searchttl;
    private javax.swing.JLabel SupplierPaymentFM_ttl;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
