package UI.Admin;

import UI.InventoryManager.InventoryManagerHomeUI;
import models.Admin;

public class AdminHomeUI extends javax.swing.JFrame {

    private Admin admin;

    public AdminHomeUI(Admin admin) {
        this.admin = admin;

        initComponents();

        usernameLabel.setText(admin.getUsername());
        userIDLabel.setText(admin.getUserID());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        userIDLabel = new javax.swing.JLabel();
        userIDLabel2 = new javax.swing.JLabel();
        manageSalesManagerFunctionsButton = new javax.swing.JButton();
        manageSalesManagerFunctionsLabel = new javax.swing.JLabel();
        managePurchaseManagerFunctionsButton = new javax.swing.JButton();
        managePurchaseManagerFunctionsLabel = new javax.swing.JLabel();
        manageInventoryManagerFunctionsButton = new javax.swing.JButton();
        manageInventoryManagerFunctionsLabel = new javax.swing.JLabel();
        manageFinanceManagerFunctionsButton = new javax.swing.JButton();
        manageFinanceManagerFunctionsLabel = new javax.swing.JLabel();
        userManagementButton = new javax.swing.JButton();
        userManagementLabel = new javax.swing.JLabel();
        activityLogsManagementButton = new javax.swing.JButton();
        actitvityLogsManagementButton = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(50, 54, 57));

        usernameLabel.setBackground(new java.awt.Color(0, 0, 0));
        usernameLabel.setForeground(new java.awt.Color(225, 225, 225));
        usernameLabel.setText("username");

        userIDLabel.setForeground(new java.awt.Color(225, 225, 225));
        userIDLabel.setText("userid");
        userIDLabel.setToolTipText("");

        userIDLabel2.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(userIDLabel2)
                        .addGap(0, 15, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(userIDLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        manageSalesManagerFunctionsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/profit.png"))); // NOI18N
        manageSalesManagerFunctionsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageSalesManagerFunctionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageSalesManagerFunctionsButtonActionPerformed(evt);
            }
        });

        manageSalesManagerFunctionsLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        manageSalesManagerFunctionsLabel.setText("<html><div style='text-align: center;'>Manage Sales<br>Manager Functions</div></html>");

        managePurchaseManagerFunctionsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/cart.png"))); // NOI18N
        managePurchaseManagerFunctionsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        managePurchaseManagerFunctionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePurchaseManagerFunctionsButtonActionPerformed(evt);
            }
        });

        managePurchaseManagerFunctionsLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        managePurchaseManagerFunctionsLabel.setText("<html><div style='text-align: center;'>Manage Purchase<br>Manager Functions</div></html>");

        manageInventoryManagerFunctionsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/inventory.png"))); // NOI18N
        manageInventoryManagerFunctionsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageInventoryManagerFunctionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageInventoryManagerFunctionsButtonActionPerformed(evt);
            }
        });

        manageInventoryManagerFunctionsLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        manageInventoryManagerFunctionsLabel.setText("<html><div style='text-align: center;'>Manage Inventory<br>Manager Functions</div></html>");

        manageFinanceManagerFunctionsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/accounting.png"))); // NOI18N
        manageFinanceManagerFunctionsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageFinanceManagerFunctionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageFinanceManagerFunctionsButtonActionPerformed(evt);
            }
        });

        manageFinanceManagerFunctionsLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        manageFinanceManagerFunctionsLabel.setText("<html><div style='text-align: center;'>Manage Finance<br>Manager Functions</div></html>");

        userManagementButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/user-group.png"))); // NOI18N
        userManagementButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userManagementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userManagementButtonActionPerformed(evt);
            }
        });

        userManagementLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        userManagementLabel.setText("<html><div style='text-align: center;'>User<br>Management</div></html>");

        activityLogsManagementButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/log-files.png"))); // NOI18N
        activityLogsManagementButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        activityLogsManagementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activityLogsManagementButtonActionPerformed(evt);
            }
        });

        actitvityLogsManagementButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        actitvityLogsManagementButton.setText("<html><div style='text-align: center;'>Activity Log<br>Management</div></html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manageSalesManagerFunctionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(manageSalesManagerFunctionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(managePurchaseManagerFunctionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(managePurchaseManagerFunctionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manageInventoryManagerFunctionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(manageInventoryManagerFunctionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(manageFinanceManagerFunctionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(manageFinanceManagerFunctionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userManagementButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userManagementLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(activityLogsManagementButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(actitvityLogsManagementButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(manageSalesManagerFunctionsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manageSalesManagerFunctionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(manageInventoryManagerFunctionsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manageInventoryManagerFunctionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(managePurchaseManagerFunctionsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(managePurchaseManagerFunctionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(manageFinanceManagerFunctionsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manageFinanceManagerFunctionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(userManagementButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userManagementLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(activityLogsManagementButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(actitvityLogsManagementButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        manageSalesManagerFunctionsLabel.getAccessibleContext().setAccessibleName("<html><div style='text-align: center;'>This is line 1.<br>This is line 2.<br>This is line 3.</div></html>");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manageSalesManagerFunctionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageSalesManagerFunctionsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageSalesManagerFunctionsButtonActionPerformed

    private void managePurchaseManagerFunctionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePurchaseManagerFunctionsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_managePurchaseManagerFunctionsButtonActionPerformed

    private void manageInventoryManagerFunctionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageInventoryManagerFunctionsButtonActionPerformed
        new InventoryManagerHomeUI(admin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_manageInventoryManagerFunctionsButtonActionPerformed

    private void manageFinanceManagerFunctionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageFinanceManagerFunctionsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageFinanceManagerFunctionsButtonActionPerformed

    private void userManagementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userManagementButtonActionPerformed
        new UserManagementUI(admin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_userManagementButtonActionPerformed

    private void activityLogsManagementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activityLogsManagementButtonActionPerformed
        new ActivityLogManagement(admin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_activityLogsManagementButtonActionPerformed

    public static void main(String args[]) {

//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AdminHomeUI().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actitvityLogsManagementButton;
    private javax.swing.JButton activityLogsManagementButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton manageFinanceManagerFunctionsButton;
    private javax.swing.JLabel manageFinanceManagerFunctionsLabel;
    private javax.swing.JButton manageInventoryManagerFunctionsButton;
    private javax.swing.JLabel manageInventoryManagerFunctionsLabel;
    private javax.swing.JButton managePurchaseManagerFunctionsButton;
    private javax.swing.JLabel managePurchaseManagerFunctionsLabel;
    private javax.swing.JButton manageSalesManagerFunctionsButton;
    private javax.swing.JLabel manageSalesManagerFunctionsLabel;
    private javax.swing.JLabel userIDLabel;
    private javax.swing.JLabel userIDLabel2;
    private javax.swing.JButton userManagementButton;
    private javax.swing.JLabel userManagementLabel;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
